### ISSUE TITLE
Add per-crate coverage tracking and thresholds

### ISSUE THREAD

**Issue by nschoonbroodt** [nschoonbroodt/rusty-assets#40]
## Overview

Implement separate coverage tracking for each crate in the workspace with individual thresholds and reporting.

## Current Situation

Coverage is currently tracked at the workspace level. All crates (assets-core, assets-cli, assets-demo) are measured together in a single report.

## Goals

- **Individual crate reports**: Generate separate coverage reports for each crate
- **Different thresholds**: Set appropriate coverage targets per crate based on their purpose
- **Granular tracking**: Monitor coverage progress for each component independently

## Proposed Thresholds

Based on the original analysis in #27:
- **assets-core**: 80% (business logic - highest standard)
- **assets-cli**: 70% (CLI commands - user interface code)
- **assets-demo**: 60% (demo/example code - less critical)

### Option 1: Multiple CI Jobs
```yaml
- name: Coverage - Core
  run: cargo llvm-cov --package assets-core --cobertura --output-path coverage-core.xml
- name: Coverage - CLI  
  run: cargo llvm-cov --package assets-cli --cobertura --output-path coverage-cli.xml
- name: Coverage - Demo
  run: cargo llvm-cov --package assets-demo --cobertura --output-path coverage-demo.xml
```

### Option 2: Single Job with Package Filtering
```yaml
- name: Generate per-crate coverage
  run: |
    cargo llvm-cov --package assets-core --html --output-dir target/coverage/core
    cargo llvm-cov --package assets-cli --html --output-dir target/coverage/cli
    cargo llvm-cov --package assets-demo --html --output-dir target/coverage/demo
```

### Option 3: Custom Scripting
- Shell script to iterate through packages
- Aggregate results with proper thresholds
- Upload separate reports to Codecov

## Benefits

- **Targeted improvements**: Focus testing efforts on specific components
- **Quality gates**: Prevent merging when core business logic lacks coverage
- **Better visibility**: Understand which parts of the system need attention
- **Flexible standards**: Different coverage expectations for different types of code

## Technical Requirements

- [ ] Generate separate coverage reports per crate
- [ ] Set up individual thresholds for CI status checks
- [ ] Upload per-crate data to Codecov (if supported)
- [ ] Document per-crate coverage commands for local development
- [ ] Add status checks to prevent regression below thresholds

## Success Criteria

- [ ] Each crate has individual coverage tracking
- [ ] CI fails if any crate falls below its threshold
- [ ] Developers can generate per-crate reports locally
- [ ] Coverage trends visible per component

## Priority

**Low** - Enhancement that improves granularity but core coverage tracking is already functional.

**Related**: #27 (parent issue - test coverage measurement)
